### ISSUE TITLE
Move Mysql code to here

### ISSUE THREAD

**Issue by rourke750** [Civcraft/CivModCore#1]

**Comment by ttk2** [comment]
with a connection pool and everything else fancy.

**Comment by ttk2** [comment]
also do remember with sharding some plugins will be on different databases so it needs a full list.

**Comment by rourke750** [comment]
Each plugin will still have it's own stuff.

**Comment by ProgrammerDan** [comment]
Is this important for our release targets?

**Comment by erocs** [comment]
No, each plugin currently deals with mysql on it's own. This is just QOL refactoring.

**Comment by goeppes** [comment]
So this is old and I don't know much, but I'm curious as to what you guys were going to do with this. If you were planning to switch to connection pooling from the current single-connection implementation, I don't really see what there would be to move here (unless you were to implement your own connection pool).

**Comment by rourke750** [comment]
My idea was just to move the Database class that most of our plugins use to here.  And switch the imports to reflect that in other plugins.

**Comment by goeppes** [comment]
So this had nothing to do with connection pooling? It was just for plugins that use the single-connection implementation?

**Comment by Maxopoly** [comment]
Yeah, this was just meant to provide a nice API, which other plugins could use.

**Comment by goeppes** [comment]
So now that there is the ManagedDatasource, is there still a need for this?
