### ISSUE TITLE
Add NMS class loader API

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/CivModCore#17]
Make the stuff NameLayer is doing right now to retain version compability a bit more general to offer an API that allows making more of our core plugins compatible with older versions.

**Comment by ProgrammerDan** [comment]
What do you have in mind for this?

**Comment by Maxopoly** [comment]
I havent looked at how Namelayer does the class loading, but just wanted to put something here that minimizes the work we have to do if we want to do the same for other plugins as well. Maybe dummy poms?
