### ISSUE TITLE
Remove CustomConversation class and replace with Bukkit Conversation API

### ISSUE THREAD

**Issue by goeppes** [Civcraft/CivModCore#18]
The sole purpose of the [CustomConversation](https://github.com/Civcraft/CivModCore/blob/master/src/vg/civcraft/mc/civmodcore/chatDialog/CustomConversation.java) class seems to be to allow the setting of the modal field. This is unnecessary though, as this is meant to be done using the [ConversationFactory](https://jd.bukkit.org/org/bukkit/conversations/ConversationFactory.html). 

I assume whoever made this class didn't actually read up on the [Conversation API](https://docs.google.com/document/d/1ofTMA6dv7Vk3v4kKhLTC1sUooHgTq71ti44AI09OsNM/edit). Unless there is a problem with the Conversation Factory?

**Comment by Maxopoly** [comment]
Yeah, but then we have to make a new factory for every single conversation, which breaks the pattern as well

**Comment by goeppes** [comment]
Which pattern? 

Also the API says you're meant to instantiate a new factory for each distinct conversation so I don't see how that's a problem?

**Comment by Maxopoly** [comment]
Hmm I'd assume that the factory here is implementing a variation of the factory pattern, where one factory instance is used to create many similarish products. The fact that the official documentation says you're supposed to create a new factory every time makes me think that that's wrong though, maybe it's just naming coincidence or used wrong.

Anyway, if you make a PR to change it, I'll merge it, but as long as it's working and the end result is the same, I dont really care too much tbh.

**Comment by ProgrammerDan** [comment]
@tyrothalos I'd support that PR. I had previously directed Max to the API you reference as I use it in EasyHelpOp and it's quite simple.

@Maxopoly The factory pattern is just a formalism for "Using a tool to create objects"; there are several implementations of the factory pattern. In this case its just useful for safely exposing all the Conversation features in a consistent way. It's also pretty easy to read: https://github.com/DevotedMC/EasyHelpOP/blob/master/src/com/bigbrainiac10/easyhelpop/viewmenu/ViewMenu.java#L114

**Comment by goeppes** [comment]
Yeah the name is misleading since it actually uses the builder pattern and not factory. 

I can make a PR later and fix it. What is the Dialog class used for anyway?

**Comment by ProgrammerDan** [comment]
> builder pattern 

There we go. Couldn't remember it.

**Comment by Maxopoly** [comment]
Easy API for reading a single line of text from chat, for example when creating groups via namelayer gui

**Comment by Maxopoly** [comment]
Example:
https://github.com/Civcraft/NameLayer/blob/master/NameLayerMain/src/vg/civcraft/mc/namelayer/gui/MainGroupGUI.java#L877

You only need to specify the actual logic and dont need to care about any of the dialog stuff behind it. It also adds configurable tab completion as a feature to them.
