### ISSUE TITLE
ConnectionPool class is unnecessary

### ISSUE THREAD

**Issue by goeppes** [Civcraft/CivModCore#24]
Is the [ConnectionPool](https://github.com/Civcraft/CivModCore/blob/master/src/main/java/vg/civcraft/mc/civmodcore/dao/ConnectionPool.java) class really needed? It appears to just wrap around HikariDataSource, but HikariDataSource itself is the connection pool. ConnectionPool does not have a meaningful purpose.

Instead of wrapping the DataSource with ConnectionPool, why not expose it directly? At best the class only offers some validation when setting up a HikariDataSource, but this can be handled by a static utility method that returns a DataSource. There should be no need for a wrapper class.

**Comment by ProgrammerDan** [comment]
It's the kiddie gloves around Hikari for the devs who aren't comfortable with doing it themselves.

Ultimately it will be wrapped as a ConfigurationSerializable for easier framework assisted instantiation.

**Comment by goeppes** [comment]
Why are kiddie gloves needed for the DataSource? Like I said, a static utility method can be used to instantiate the DataSource if that is what people are uncomfortable with, but handling the actual [DataSource](https://docs.oracle.com/javase/7/docs/api/javax/sql/DataSource.html) instance itself is not even as complex as using a Logger. 

It doesn't appear that any plugins even directly use the ConnectionPool, it's only indirectly through the ManagedDatasource class. ConnectionPool has no functionality that warrants a class of its own, just have the ManagedDatasource access a DataSource directly and add another function to help initialize.

Using ConfigurationSerializable here would be abusing the config API. While it might be handy to deserialize the DataSource from a config, it doesn't make sense to serialize a DataSource to a config. I guess it would still work and isn't really a problem except that it couples more code to the Bukkit API and might make automated testing more of a pain.

Also it might be good to enable prepared statement caching.

**Comment by ProgrammerDan** [comment]
I get where you're coming from, but I don't understand your insistence. Or objections to "serialization" -- literally just would provide an easy way to "wrap" the configuration instantiate the connection pool.

Have you seen our existing database patterns? Kiddie gloves are badly needed.

The class you're focusing on harms nothing.

W.r.t. Prepared Statement Caching should be enabled driver side as HikariCP iirc doesn't do anything additional. I'll look into it further.

**Comment by goeppes** [comment]
Unnecessary code is bad code. The more bad code there is, the longer it takes to read and understand the code, the harder it is to use the code, the more places there could be issues, and the longer it takes to fix problems. Do you disagree with this?

I don't know why you think using ConfigurationSerializable is better. Yes, it would work, but having a single static utility method vs implementing the ConfigurationSerializable, both would do pretty much the same thing but the single method would be much less code.

What do the kiddie gloves help with? What mistakes does it prevent a developer from making?

For prepared statement caching, you [configure the driver through HikariCP](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration).

EDIT: Also when using ConfigurationSerializable, if for some reason there is an error while deserializing (i.e. field does not exist in config, typo, etc), it cannot send the exception to the method calling the deserialization, everything gets swallowed.

**Comment by Maxopoly** [comment]
If the class wasn't in CivModCore, an exact copy of it would just slowly end up getting copied in every plugin, same thing as the current Database class. 

It's just an utility to make using the whole thing as easy as possible and can be used as blockbox database connection, just like the current Database class, but done right this time.

**Comment by goeppes** [comment]
There is absolutely zero need to copy anything to any plugin, the DataSource implementation is provided by the HikariCP dependency. We don't need to write a class to wrap around the actual thing that has all of the functionality we need.

**Comment by ProgrammerDan** [comment]
There's two big goals here.

Goal #1: Provide ManagedDatasource to encapsulate the "major features" of a ConnectionPool (In this case, HikariCP) while insulating the developer from having to know all the details. This class includes the "most important" configuration details in its constructor, and offers simple Migration support and version tracking baked it. In short, it's the Kiddie Gloves, and I think it'll do its job just fine.

Goal #2: Eventually, some folks might want to do some more advanced things, perhaps take the training wheels off, but not all the way.

The current ConnectionPool class is meant to achieve Goal #2. It doesn't, yet ... but I also wanted to get something usable out the door. Now that it's coded and used in NameLayer, I can continue to iterate and improve it, and so can others.

I'm not at all opposed to exposing the underlying pool, or eliminating ConnectionPool entirely. I had a very specific initial use-case in mind for it, but if it offends too much we can remove it :)

**Comment by ProgrammerDan** [comment]
@tyrothalos check PR #25 -- might be more comfortable kiddie gloves for us without sacrificing anything for junior devs

**Comment by erocs** [comment]
No, we need to encapsulate / abstract whatever connection pool we use. CivModCore will hand out db connections and the plugins won't care about how they are managed under the covers.
1. If we want to change to another manager later, this abstraction is better.
2. With all the shading going on, if plugin A loads one class from version 1 and plugin B loads the second class from version 2, I don't want to track down the bug,  however that would manifest in hikari.
3. One example, one way to do it. Keep everyone focused in the same direction and uniform.
4. Every plugin shouldn't have to deal with writing the identical bootstrapping code.

**Comment by ProgrammerDan** [comment]
What do you think of my changes in #25 @erocs -- doesn't achieve 1, but largely preserves the achievements of 2-4.

I could alter the getDatasource method to return the interface java.sql.Datasource (so it's replaceable); The config is harder to generalize, but I want to wrap it anyway to allow serialization of the configuration more directly (vs. the Datasource entirely; this pattern will be more generally applicable).

**Comment by goeppes** [comment]
@erocs The [DataSource](https://docs.oracle.com/javase/7/docs/api/javax/sql/DataSource.html) interface is the abstraction, is it not? 
1. If we want to change to another manager later, we just have to switch DataSource implementations instead of writing another wrapper for another implementation. 
2. I am not sure what you mean by this. CivModCore should be the only plugin managing DataSource implementations directly, all other plugins should use the abstraction, correct?
3. Writing a wrapper for a DataSource implementation is inventing a new way to do it. Just using the existing way is best, no?
4. Every plugin doesn't need to write bootstrapping code, just CivModCore. However, one of my points is that this can be done with a single method, we do not need an entirely new class for each.

**Comment by goeppes** [comment]
@ProgrammerDan You can move the HikariCP specific stuff out of the ManagedDatasource and into a method like I've been saying. For example:

``` java
public final class DataSourceFactory {

    public static DataSource createHikariDataSource(Configuration bukkitConfig) {
        HikariConfig config = new HikariConfig();
        ...
        return new HikariDataSource(config);
    }

}
```

And then ManagedDatasource just calls `createHikariDataSource()` to get an instance. ManagedDatasource is then almost completely decoupled from the HikariCP DataSource implementation. The only issue is when you need to close the connection pool.

**Comment by ProgrammerDan** [comment]
Why would closing represent an issue?

I'll consider this approach.

**Comment by goeppes** [comment]
The java.sql.DataSource does not have a close method, I forgot to mention. You would need to check the DataSource instance and make sure it implements Closeable before casting and closing. Not too much of a problem, now that I think about it.

**Comment by erocs** [comment]
If all this is only about how hikari is abstracted within CivModCore itself then I don't care how it's done. It doesn't particularly matter. If I misread that you wanted every plugin to directly use hikari my apologies. Been running around / without power and a phone is a poor computer substitute.

My goals with any of this.
- The 3rd party pool manager isn't shaded into every single plugin, only CivModCore.
- All plugins use the same connection pool to reduce our connection count.
- Abstract/write helpers / document as much as we can to assist programmers unfamiliar with this area.
- Unify all the plugins behind this to remove the issues that plague us.

If all you want is to change hidden framework that doesn't affect CivModCore's api or semantics, feel free to send a pull as it doesn't alter what I care about in Dan's changes.  :)

**Comment by ProgrammerDan** [comment]
> All plugins use the same connection pool to reduce our connection count.

Fine with all goals but this one, this is a terrible idea. Badly behaved plugins can starve out the pool.

**Comment by erocs** [comment]
And we hit the connection count because of all the separate connections laying around. If there's some sharing we won't have so many laying around and I assume we can configure the pool to create more until the db dies from load.

**Comment by tyrothalos** [comment]
[Brett Wooldridge on pool sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing).

It seems that many smaller pools is much more efficient that one giant pool.
