### ISSUE TITLE
Multiple click types for Clickables

### ISSUE THREAD

**Issue by Sharpcastle33** [Civcraft/CivModCore#29]
It'd be tremendously useful for Clickables ```clicked``` events to pass the click type from Bukkit's InventoryClickEvents into your ```clicked``` method, so developers can have multiple outcomes for different types of clicks.

**Comment by Maxopoly** [comment]
See https://github.com/CivClassic/CivModCore/commit/4092a0585e2759d36e84eefca5cf7d62d7f8f961
