### ISSUE TITLE
Add setCommandHandler method

### ISSUE THREAD

**Issue by rourke750** [Civcraft/CivModCore#4]
This code here https://github.com/Civcraft/CivModCore/blob/master/src/vg/civcraft/mc/civmodcore/ACivMod.java#L21
instead of having handle = PluginCommandHandler();

have a abstract method called setCommandHandler(CommandHandler handle) that more easily notifies plugin writes to set the commandhandler.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/CivModCore/blob/config-impv/src/vg/civcraft/mc/civmodcore/ACivMod.java#L150
